apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: springboot
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring-con
        image: vinay1908/spring-boot:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
