apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  selector:
    matchLabels:
      app: spring-2
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: spring-2
    spec:
      containers:
      - name: spring-con2
        image: vinay1908/spring-app-1:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
