apiVersion: v1
kind: Service
metadata:
  name: springsvc-2
  labels:
    app: spring-2
spec:
  selector:
    app: spring-2
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31201
