apiVersion: v1
kind: Service
metadata:
  name: springservice2
  labels:
    app: springsvc2
spec:
  selector:
    app: springsvc2
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31201
