apiVersion: v1
kind: Service
metadata:
  name: springsvc
  labels:
    app: spring
spec:
  selector:
    app: spring
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
